# Startup settings (optional, adjust as needed)
start-at-login = false  # Set to true if you want Aerospace to launch at login
after-login-command = []  # Empty by default
after-startup-command = []  # Add 'exec-and-forget borders' or 'exec-and-forget sketchybar' if you use them

# General settings
default-root-container-layout = 'tiles'  # Default tiling layout
default-root-container-orientation = 'auto'  # Auto-orient tiles
accordion-padding = 30  # Padding for accordion layout
enable-normalization-flatten-containers = true  # Flatten nested containers
enable-normalization-opposite-orientation-for-nested-containers = true  # Opposite orientation for nesting
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']  # Multi-monitor mouse behavior (optional)

# Gaps (customized from your preference)
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

# Key bindings
[mode.main.binding]
# Workspace switching (your named workspaces)
alt-d = 'workspace design'    # Design workspace
alt-t = 'workspace trading'   # Trading workspace
alt-v = 'workspace dev'       # Development workspace
alt-m = 'workspace main'      # Main workspace (Notion)
alt-b = 'workspace browser'   # Browser workspace
alt-u = 'workspace music'     # Music workspace

# Move windows to workspaces
alt-shift-d = 'move-node-to-workspace design'
alt-shift-t = 'move-node-to-workspace trading'
alt-shift-v = 'move-node-to-workspace dev'
alt-shift-m = 'move-node-to-workspace main'
alt-shift-b = 'move-node-to-workspace browser'
alt-shift-u = 'move-node-to-workspace music'

# Navigation within workspace
alt-h = 'focus left'          # Focus left window
alt-j = 'focus down'          # Focus window below
alt-k = 'focus up'            # Focus window above
alt-l = 'focus right'         # Focus right window
alt-shift-h = 'move left'     # Move window left
alt-shift-j = 'move down'     # Move window down
alt-shift-k = 'move up'       # Move window up
alt-shift-l = 'move right'    # Move window right

# Cycling within workspace
alt-tab = 'focus next'        # Cycle to next app in workspace
alt-shift-tab = 'focus prev'  # Cycle to previous app in workspace

# Layout toggles
alt-slash = 'layout tiles horizontal vertical'  # Tile layout
alt-comma = 'layout accordion horizontal vertical'  # Accordion layout
alt-f = 'layout full'         # Full-screen toggle

# Resize windows
alt-minus = 'resize smart -50'  # Shrink window
alt-equal = 'resize smart +50'  # Expand window

# App launching with workspace switching
# Design workspace
alt-shift-f = 'exec-and-forget open -a Figma; workspace design'              # Figma
alt-shift-s = 'exec-and-forget open -a Spline; workspace design'             # Spline
alt-shift-i = 'exec-and-forget open -a "Adobe Illustrator"; workspace design'  # Illustrator
alt-shift-p = 'exec-and-forget open -a "Adobe Photoshop"; workspace design'    # Photoshop

# Trading workspace
alt-shift-g = 'exec-and-forget open -a Telegram; workspace trading'          # Telegram
alt-shift-x = 'exec-and-forget open -a Discord; workspace trading'           # Discord (optional)
alt-shift-r = 'exec-and-forget open -a TradingView; workspace trading'       # TradingView
alt-shift-a = 'exec-and-forget open -a Arc; workspace trading'               # Arc

# Dev workspace
alt-shift-c = 'exec-and-forget open -a Cursor; workspace dev'                # Cursor
alt-shift-v = 'exec-and-forget open -a "Visual Studio Code"; workspace dev'  # VS Code
alt-shift-t = '''exec-and-forget osascript -e 'tell application "Terminal" to do script'; workspace dev'''  # Terminal

# Main workspace
alt-shift-n = 'exec-and-forget open -a Notion; workspace main'               # Notion

# Browser workspace
alt-shift-w = 'exec-and-forget open -a Safari; workspace browser'            # Safari
alt-shift-e = 'exec-and-forget open -a "Google Chrome"; workspace browser'   # Chrome
alt-shift-q = 'exec-and-forget open -a Firefox; workspace browser'           # Firefox

# Music workspace (BTT-style binding)
right-option-i = 'exec-and-forget open -a Music; workspace music'            # Music (iTunes)

# Reload config
alt-shift-c = 'reload-config'  # Reloads aerospace.toml

# Optional service mode (for advanced commands)
[mode.service.binding]
esc = ['reload-config', 'mode main']  # Reload and exit service mode
r = ['flatten-workspace-tree', 'mode main']  # Reset layout
f = ['layout floating tiling', 'mode main']  # Toggle floating/tiling
backspace = ['close-all-windows-but-current', 'mode main']  # Close all but current
alt-shift-semicolon = 'mode service'  # Enter service mode (place in [mode.main.binding])